ROTATE_DEFAULT = 0
ZOOM_DEFAULT = 0
FLIP_OPTIONS = ['None', 'X', 'Y', 'Both']
BLUR_DEFAULT = 0
CONTRAST_DEFAULT = 0
EFFECT_OPTIONS = ['None', 'Emboss', 'Find Edges', 'Contour', 'Edge enhance']
BRIGHTNESS_DEFAULT = 1
VIBRANCE_DEFAULT = 1
GRAYSCALE_DEFAULT = False
INVERT_DEFAULT = False

# COLORS
WHITE = '#FFF'
GREY = 'grey'
BLUE = '#1f6aa5'
DARK_GRAY = '#4a4a4a'
CLOSE_RED = "#8a0606"

SLIDER_BG = '#64686b'
